/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   maintest1.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: rtulchiy <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/12/06 14:55:05 by rtulchiy          #+#    #+#             */
/*   Updated: 2017/12/25 14:44:01 by vludan           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include "ft_printf.h"

int		main(void)
{
	char	*test = "unit";

	printf("-------------SIMPLE------------\n");
	printf("or_just a text:%d blablacar. UNTI %u!!", 42, 42);
	printf("\n");
	ft_printf("ft_just a text:%d blablacar. UNTI %u!!", 42, 42);
	printf("\n\n");
	printf("-------------FLAGS------------\n");
	printf("or_just a text:|%+d|", 42);
	printf("\n");
	ft_printf("ft_just a text:|%+d|", 42);
	printf("\n\n");
	printf("or_just a text:|%.12d|", 42);
	printf("\n");
	ft_printf("ft_just a text:|%.12d|", 42);
	printf("\n\n");
	printf("or_just a text:|%+.5d|", 42);
	printf("\n");
	ft_printf("ft_just a text:|%+.5d|", 42);
	printf("\n\n");
	printf("or_just a text:|%13.5d|", 42);
	printf("\n");
	ft_printf("ft_just a text:|%13.5d|", 42);
	printf("\n\n");
	printf("or_just a text:|%013.5d|", 42);
	printf("\n");
	ft_printf("ft_just a text:|%013.5d|", 42);
	printf("\n\n");
	printf("or_just a text:|%+13.5d|", 42);
	printf("\n");
	ft_printf("ft_just a text:|%+13.5d|", 42);
	printf("\n\n");
	printf("or_just a text:%-13.5d!", 42);
	printf("\n");
	ft_printf("ft_just a text:%-13.5d!", 42);
	printf("\n\n");
	printf("or_just a text:%-013.5d!", 42);
	printf("\n");
	ft_printf("ft_just a text:%-013.5d!", 42);
	printf("\n\n");
	printf("or_just a text:%-+013.5d!", 42);
	printf("\n");
	ft_printf("ft_just a text:%-+013.5d!", 42);
	printf("\n\n");
	printf("or_just a text:% 013d!", 42);
	printf("\n");
	ft_printf("ft_just a text:% 013d!", 42);
	printf("\n\n");
	printf("or_just a text:|%+d|", -42);
	printf("\n");
	ft_printf("ft_just a text:|%+d|", -42);
	printf("\n\n");
	printf("or_just a text:|%.12d|", -42);
	printf("\n");
	ft_printf("ft_just a text:|%.12d|", -42);
	printf("\n\n");
	printf("or_just a text:|%+.5d|", -42);
	printf("\n");
	ft_printf("ft_just a text:|%+.5d|", -42);
	printf("\n\n");
	printf("or_just a text:|%13.5d|", -42);
	printf("\n");
	ft_printf("ft_just a text:|%13.5d|", -42);
	printf("\n\n");
	printf("or_just a text:|%013.5d|", -42);
	printf("\n");
	ft_printf("ft_just a text:|%013.5d|", -42);
	printf("\n\n");
	printf("or_just a text:|%+13.5d|", -42);
	printf("\n");
	ft_printf("ft_just a text:|%+13.5d|", -42);
	printf("\n\n");
	printf("or_just a text:%-13.5d!", -42);
	printf("\n");
	ft_printf("ft_just a text:%-13.5d!", -42);
	printf("\n\n");
	printf("or_just a text:%-013.5d!", -42);
	printf("\n");
	ft_printf("ft_just a text:%-013.5d!", -42);
	printf("\n\n");
	printf("or_just a text:%-+013.5d!", -42);
	printf("\n");
	ft_printf("ft_just a text:%-+013.5d!", -42);
	printf("\n\n");
	printf("or_just a text:% +013d!", 42);
	printf("\n");
	ft_printf("ft_just a text:% +013d!", 42);
	printf("\n\n");
	printf("-------------NUMS------------\n");	
	printf("or_just a text:%d", 42);
	printf("\n");
	ft_printf("ft_just a text:%d", 42);
	printf("\n\n");
	printf("or_just a text:%d", 4000000999);
	printf("\n");
	ft_printf("ft_just a text:%d", 4000000999);
	printf("\n\n");
	printf("or_just a text:%d %d %d", 5234, 65432, 1234567);
	printf("\n");
	ft_printf("ft_just a text:%d %d %d", 5234, 65432, 1234567);
	printf("\n\n");
	printf("or_just a text:%u", 3000000000);
	printf("\n");
	ft_printf("ft_just a text:%u", 3000000000);
	printf("\n\n");
	printf("or_just a text:%u", -142);
	printf("\n");
	ft_printf("ft_just a text:%u", -142);
	printf("\n\n");
	printf("or_just a text:%u", 5000000000);
	printf("\n");
	ft_printf("ft_just a text:%u", 5000000000);
	printf("\n\n");
	printf("or_just a text:%hhu", 255);
	printf("\n");
	ft_printf("ft_just a text:%hhu", 255);
	printf("\n\n");
	printf("or_just a text:%hu", 1200);
	printf("\n");
	ft_printf("ft_just a text:%hu", 1200);
	printf("\n\n");
	printf("or_just a text:%lu", 5000000999);
	printf("\n");
	ft_printf("ft_just a text:%lu", 5000000999);
	printf("\n\n");
	printf("or_just a text:%llu", 10000000000);
	printf("\n");
	ft_printf("ft_just a text:%llu", 10000000000);
	printf("\n\n");
	printf("or_just a text:%llu", 999999999999999);
	printf("\n");
	ft_printf("ft_just a text:%llu", 999999999999999);
	printf("\n\n");
	printf("or_just a text:%d", 3000000000);
	printf("\n");
	ft_printf("ft_just a text:%d", 3000000000);
	printf("\n\n");
	printf("or_just a text:%d", -142);
	printf("\n");
	ft_printf("ft_just a text:%d", -142);
	printf("\n\n");
	printf("or_just a text:%d", 5000000000);
	printf("\n");
	ft_printf("ft_just a text:%d", 5000000000);
	printf("\n\n");
	printf("or_just a text:%hhd", 255);
	printf("\n");
	ft_printf("ft_just a text:%hhd", 255);
	printf("\n\n");
	printf("or_just a text:%hd", 1200);
	printf("\n");
	ft_printf("ft_just a text:%hd", 1200);
	printf("\n\n");
	printf("or_just a text:%ld", 5000000999);
	printf("\n");
	ft_printf("ft_just a text:%ld", 5000000999);
	printf("\n\n");
	printf("or_just a text:%lld", 10000000000);
	printf("\n");
	ft_printf("ft_just a text:%lld", 10000000000);
	printf("\n\n");
	printf("or_just a text:%lld", 9999999999999999999);
	printf("\n");
	ft_printf("ft_just a text:%lld", 9999999999999999999);
	printf("\n\n");
	printf("-------------RANDOM------------\n");
	printf("or_just a text:|%#x|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#x|", 1488);
	printf("\n\n");
	printf("or_just a text:|%#X|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#X|", 1488);
	printf("\n\n");
	printf("or_just a text:|%#10x|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#10x|", 1488);
	printf("\n\n");
	printf("or_just a text:|%#010x| and that's all. %u", 1488, -42);
	printf("\n");
	ft_printf("ft_just a text:|%#010x| and that's all. %u", 1488, -42);
	printf("\n\n");
	printf("or_just a text:|%#.10X|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#.10X|", 1488);
	printf("\n\n");
	printf("or_just a text:|%0#4x|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%0#4x|", 1488);
	printf("\n\n");
	printf("or_just a text:|%#8x|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#8x|", 1488);
	printf("\n\n");
	printf("or_just a text:|%0#5.4x|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%0#5.4x|", 1488);
	printf("\n\n");
	printf("or_just a text:|%o|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%o|", 1488);
	printf("\n\n");
	printf("or_just a text:|%#o|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#o|", 1488);
	printf("\n\n");
	printf("or_just a text:|%#10o|", 1488);
	printf("\n");
	ft_printf("ft_just a text:|%#10o|", 1488);
	printf("\n\n");
	printf(" ret = %d;", printf("or_just a text:%s %d %c %c", test, 42, 'R', 'T'));
	printf("\n");
	ft_printf(" ret = %d;", ft_printf("ft_just a text:%s %d %c %c", test, 42, 'R', 'T'));
	printf("\n\n");
	printf("or_just a text:|%20.15p|", (void*)18446744073709551615);
	printf("\n");
	ft_printf("ft_just a text:|%20.15p|", (void*)18446744073709551615);
	printf("\n\n");
	printf("or_just a text:%D", 4000000000);
	printf("\n");
	ft_printf("ft_just a text:%D", 4000000000);
	printf("\n\n");
	printf("or_just a text:|%#20O|", 4000000000);
	printf("\n");
	ft_printf("ft_just a text:|%#20O|", 4000000000);
	printf("\n\n");
	printf("or_just a text:%U", 8000000000);
	printf("\n");
	ft_printf("ft_just a text:%U", 8000000000);
	printf("\n\n");
	printf("or_just a text:|%015.8s|", "cut text unit work");
	printf("\n");
	ft_printf("ft_just a text:|%015.8s|", "cut text unit work");
	printf("\n\n");
	return (0);
}
